---
- name: Create Grafana data directory
  file:
    path: "{{ grafana_data_dir }}"
    state: directory
    mode: '0755'

- name: Set Grafana directory permissions
  file:
    path: "{{ grafana_data_dir }}"
    owner: '472'
    group: '472'
    mode: '0755'
    recurse: yes

- name: Pull Grafana Docker image
  docker_image:
    name: "{{ grafana_image }}:{{ grafana_version }}"
    source: pull
  become: yes
  retries: 3
  delay: 5

- name: Stop existing Grafana container
  docker_container:
    name: "{{ grafana_container_name }}"
    state: stopped
  ignore_errors: yes

- name: Remove existing Grafana container
  docker_container:
    name: "{{ grafana_container_name }}"
    state: absent
  ignore_errors: yes

- name: Create and start Grafana container
  docker_container:
    name: "{{ grafana_container_name }}"
    image: "{{ grafana_image }}:{{ grafana_version }}"
    state: started
    restart_policy: always
    ports:
      - "{{ grafana_port }}:3000"
    volumes:
      - "{{ grafana_data_dir }}:/var/lib/grafana"
    env:
      GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
      GF_USERS_ALLOW_SIGN_UP: "false"
